name: Build APK

on:
  push:
    branches:
      - main     # ou a branch que você usa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências JS
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Setup Android SDK e JDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 31
          target: android-31
          jdk-version: 17

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
