-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 19:52:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SALV
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SALV` ;

-- -----------------------------------------------------
-- Schema SALV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SALV` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `SALV` ;

-- -----------------------------------------------------
-- Table `SALV`.`Tb_Usuários`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SALV`.`Tb_Usuários` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SALV`.`Tb_Usuários` (
  `ID_Usuários` INT NOT NULL,
  `Nome` VARCHAR(55) NULL,
  `Email` VARCHAR(55) NULL,
  `Celular` VARCHAR(55) NULL,
  PRIMARY KEY (`ID_Usuários`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SALV`.`Tb_Dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SALV`.`Tb_Dispositivo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SALV`.`Tb_Dispositivo` (
  `ID_Dispositivo` INT NOT NULL,
  `Localização` VARCHAR(60) NULL,
  `Status` TINYINT NULL,
  `Nome` VARCHAR(55) NULL,
  PRIMARY KEY (`ID_Dispositivo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SALV`.`Tb_Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SALV`.`Tb_Evento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SALV`.`Tb_Evento` (
  `ID_Evento` INT NOT NULL,
  `DataHora` DATETIME NULL,
  `Local` VARCHAR(55) NULL,
  `Tipo_Evento` TINYINT NULL,
  `Tb_Dispositivo_ID_Dispositivo` INT NOT NULL,
  PRIMARY KEY (`ID_Evento`, `Tb_Dispositivo_ID_Dispositivo`),
  INDEX `fk_Tb_Evento_Tb_Dispositivo1_idx` (`Tb_Dispositivo_ID_Dispositivo` ASC) VISIBLE,
  CONSTRAINT `fk_Tb_Evento_Tb_Dispositivo1`
    FOREIGN KEY (`Tb_Dispositivo_ID_Dispositivo`)
    REFERENCES `SALV`.`Tb_Dispositivo` (`ID_Dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SALV`.`Tb_Notificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SALV`.`Tb_Notificacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SALV`.`Tb_Notificacao` (
  `ID_Notificacao` INT NOT NULL,
  `Mensagem` VARCHAR(45) NULL,
  `Destino` VARCHAR(55) NULL,
  `DataHoraEnvio` DATETIME NULL,
  `Tb_Evento_ID_Evento` INT NOT NULL,
  `Tb_Evento_Tb_Dispositivo_ID_Dispositivo` INT NOT NULL,
  PRIMARY KEY (`ID_Notificacao`, `Tb_Evento_ID_Evento`, `Tb_Evento_Tb_Dispositivo_ID_Dispositivo`),
  INDEX `fk_Tb_Notificacao_Tb_Evento1_idx` (`Tb_Evento_ID_Evento` ASC, `Tb_Evento_Tb_Dispositivo_ID_Dispositivo` ASC) VISIBLE,
  CONSTRAINT `fk_Tb_Notificacao_Tb_Evento1`
    FOREIGN KEY (`Tb_Evento_ID_Evento` , `Tb_Evento_Tb_Dispositivo_ID_Dispositivo`)
    REFERENCES `SALV`.`Tb_Evento` (`ID_Evento` , `Tb_Dispositivo_ID_Dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SALV`.`Tb_Registro_de_Acesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SALV`.`Tb_Registro_de_Acesso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SALV`.`Tb_Registro_de_Acesso` (
  `ID_Registro_de_Acesso` INT NOT NULL,
  `Data e Hora` DATETIME NULL,
  `Statis_de_Acesso` TINYINT NULL,
  `Filmagem` BLOB NULL,
  `Tb_Usuários_ID_Usuários` INT NOT NULL,
  `Tb_Dispositivo_ID_Dispositivo` INT NOT NULL,
  PRIMARY KEY (`ID_Registro_de_Acesso`, `Tb_Usuários_ID_Usuários`, `Tb_Dispositivo_ID_Dispositivo`),
  INDEX `fk_Tb_Registro_de_Acesso_Tb_Usuários_idx` (`Tb_Usuários_ID_Usuários` ASC) VISIBLE,
  INDEX `fk_Tb_Registro_de_Acesso_Tb_Dispositivo1_idx` (`Tb_Dispositivo_ID_Dispositivo` ASC) VISIBLE,
  CONSTRAINT `fk_Tb_Registro_de_Acesso_Tb_Usuários`
    FOREIGN KEY (`Tb_Usuários_ID_Usuários`)
    REFERENCES `SALV`.`Tb_Usuários` (`ID_Usuários`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Registro_de_Acesso_Tb_Dispositivo1`
    FOREIGN KEY (`Tb_Dispositivo_ID_Dispositivo`)
    REFERENCES `SALV`.`Tb_Dispositivo` (`ID_Dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
